### ISSUE TITLE
Report the DebugBear test URL with `utils.status.show()`

### ISSUE THREAD

**Issue by ehmicky** [DebugBear/netlify-build-plugin-debugbear#3]
Each DebugBear test URL is currently printed on console:

https://github.com/DebugBear/netlify-build-plugin-debugbear/blob/ec2915922b8e1ec150c92f14e3257c65e20ec1a4/index.js#L56

It might make sense to use `utils.status.show()` instead (more information on this method [here](https://github.com/DebugBear/netlify-build-plugin-debugbear/blob/ec2915922b8e1ec150c92f14e3257c65e20ec1a4/index.js#L56), something like:

```js
utils.status.show({ 
  summary: `${pageIds.length} DebugBear tests in progress`,
  text: pages.map(page => `  - ${page.id}: ${page.url}`).join('\n'),
})
```

The advantages:
  - The message will be highlighted in the logs
  - The information will be shown in the deploy summary in the UI, making it more visible to UI users

**Comment by mattzeunert** [comment]
Hey @ehmicky,

I tried to use that, but I think right now it doesn't show up in the Netlify web UI, so maybe it's not a good idea?

**Comment by ehmicky** [comment]
It should show up in the deploy summary, providing this is run in production (not locally). If not, this might indicate a bug in Netlify. Did you try it in the production Netlify CI?

**Comment by ehmicky** [comment]
I think you accidentally closed #3 instead of #1 :)

**Comment by mattzeunert** [comment]
Oops, yes I did.

I've added a `utils.status.show` call, but I'm not sure where to find the output. 

Doesn't seem to be [here](https://app.netlify.com/sites/mystifying-kilby-0e6399/deploys/5f4fde6a45648c00075bf080), and it's not in the log either:

![Screenshot 2020-09-02 at 19 08 29](https://user-images.githubusercontent.com/1303660/92020232-bdc19080-ed4f-11ea-88be-8c7f404f11ec.png)

When I run the build locally I see this:

![Screenshot 2020-09-02 at 19 10 27](https://user-images.githubusercontent.com/1303660/92020424-fd887800-ed4f-11ea-9a41-6233e0fdc90f.png)

**Comment by ehmicky** [comment]
This is a bug. I have added this to our backlog so we can address it.

I would still personally suggest still using `utils.status.show()`, but combined with `console.log()`. Like this, you would get the DebugBear test URLs shown both in the plugin logs (while this bug is being fixed), but also at the end of the logs and in the deploy summary (once this bug is fixed).

**Comment by mattzeunert** [comment]
Thanks, calling both methods now.

**Comment by ehmicky** [comment]
I just filed a bug report to our front-end team (this appears to be a front-end bug). We should fix this soon!

**Comment by ehmicky** [comment]
This is fixed now!
