### ISSUE TITLE
Add error handling for the main API call

### ISSUE THREAD

**Issue by ehmicky** [DebugBear/netlify-build-plugin-debugbear#4]
The following API call:

https://github.com/DebugBear/netlify-build-plugin-debugbear/blob/c3855d63e471b12013694de6f8a8e85207e2e3e8/index.js#L49

Can fail due to user errors, such as an invalid API key:

```
Error making request POST /page/711/analyze: API key not found 
    /opt/build/repo/.netlify/plugins/node_modules/debugbear/dist/callApi.js:75:27 Object.<anonymous>
    /opt/build/repo/.netlify/plugins/node_modules/debugbear/dist/callApi.js:33:23 step
    /opt/build/repo/.netlify/plugins/node_modules/debugbear/dist/callApi.js:14:53 Object.throw
    /opt/build/repo/.netlify/plugins/node_modules/debugbear/dist/callApi.js:6:65 rejected
```

At the moment, this is reported as a plugin bug. In order to report it as a user error instead, this line of code should probably be wrapped in `try`/`catch` and use `utils.build.failPlugin()`.

**Comment by mattzeunert** [comment]
@ehmicky Thanks a lot for reporting this, have submitted a PR.

**Comment by ehmicky** [comment]
Thank you @mattzeunert!
